"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 从项目根目录的 .env 加载环境变量（含 DEEPSEEK_API_KEY，勿提交 .env）
from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

MEDIA_ROOT = BASE_DIR / 'media'      # 物理路径
MEDIA_URL  = '/media/'
RECOGNIZE_TMP_DIR = BASE_DIR / 'media' / 'recognize_tmp'
RECOGNIZE_SAVE_DIR = BASE_DIR / 'media' / 'recognize'
RFDETR_WEIGHTS_PATH = BASE_DIR / 'weights' / 'rf-detr-base.pth'
PROJECT_ROOT   = BASE_DIR                # 为可读性再起一个别名
MODELS_DIR     = PROJECT_ROOT / 'chat' / 'models'
LOCATOR_DIR    = PROJECT_ROOT / 'locator'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-5!#m#x5=nsgw8j-y$^9=%)#fky8h&y-l_x=39d3dsvj&q_ui_0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 第三方
    "rest_framework",                 # DRF
    "rest_framework_simplejwt",       # JWT 认证
    'drf_spectacular',           # ⭐
    'drf_spectacular_sidecar',
    'corsheaders',
    # 本地 app
    "accounts",                       # 自定义用户 app
    'chat',
    'locator',
    'vectordb',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vue dev server
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + ["Authorization"]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    "DEFAULT_THROTTLE_RATES": {"chat": "10/min"},
}
SPECTACULAR_SETTINGS = {
    # 让 drf-spectacular 直接读取你写好的 openapi.yaml
    'SCHEMA_PATH': BASE_DIR / 'openapi.yaml'
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),     # access 1 小时
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),        # refresh 7 天
    "ROTATE_REFRESH_TOKENS": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
EMBED_MODEL_PATH = str(MODELS_DIR / 'bgem3')
RERANK_PATH  = str(MODELS_DIR / 'bge-reranker')
VECTOR_DIR = Path('vector_store')
COLLECTION_NAME = "default"
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
LOCATOR_DATASET_ROOT = str(LOCATOR_DIR / 'sift' / 'dataset')
LOCATOR_FEATURES_PATH = str(LOCATOR_DIR / 'sift' / 'val_features.pkl')
LOCATOR_LOCATIONS_MAP = str(LOCATOR_DIR / 'sift' / 'locations.json')
LOCATOR_FEATURE_TYPE = 'sift'   # 或 'orb'

# ── 文本对话：DeepSeek API（OpenAI 兼容）──
# 在 https://platform.deepseek.com/api_keys 申请 API Key，填入环境变量或此处
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat")

# ── 看图（多模态）：官方 api.deepseek.com 的 deepseek-chat 不支持 image_url ──
# 需要 OpenAI 兼容的多模态端点时可配置，例如硅基流动 / 阿里云百炼 的 Qwen-VL 等。
LOCATOR_VISION_BASE_URL = os.environ.get("LOCATOR_VISION_BASE_URL", "").strip()
LOCATOR_VISION_API_KEY = (
    os.environ.get("LOCATOR_VISION_API_KEY", "").strip()
    or os.environ.get("DEEPSEEK_API_KEY", "").strip()
)
LOCATOR_VISION_MODEL = os.environ.get("LOCATOR_VISION_MODEL", "").strip() or os.environ.get(
    "DEEPSEEK_VISION_MODEL", ""
).strip()
