# Generated by Django 5.2.4 on 2025-07-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_thread_chatlog_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="source_documents",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
